
name: CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: aeiouxx/sfml-ci:latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache cmake
      uses: actions/cache@v2
      with:
        path: |
          C:\ProgramData\chocolatey\lib\cmake
          C:\ProgramData\chocolatey\bin\cmake.exe
        key: ${{ runner.os }}-choco-cmake
    
    - name: Check cmake installed
      id: check-cmake
      run: |
        if (Test-Path "C:\ProgramData\chocolatey\bin\cmake.exe") {
          echo "CMake is already installed."
          echo "::set-output name=installed::true"
        }

    - name: Install cmake
      if: steps.check-cmake.outputs.installed != 'true'
      run: |
        choco install cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
